apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller
    app.kubernetes.io/name: hcr
    app.kubernetes.io/managed-by: kustomize
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  namespace: system
  labels:
    control-plane: controller
    app.kubernetes.io/name: hcr
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    matchLabels:
      control-plane: controller
      app.kubernetes.io/name: hcr
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller
        app.kubernetes.io/name: hcr
    spec:
      serviceAccountName: controller
      terminationGracePeriodSeconds: 10
      automountServiceAccountToken: true    
      securityContext:
        fsGroup: 1001    
      containers:
      - command:
        - /controller
        args:
          - --leader-elect
          - --health-probe-bind-address=:8081
        image: controller
        env:
        - name: LOGGER_LEVEL
          value: debug        
        name: manager
        ports: []
        securityContext:
          runAsUser: 1001
          runAsGroup: 1001  
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - "ALL"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts: []
      - name: docbase
        image: docbase
        env:
        - name: ENABLE_PDF_EXPORT
          value: "1"    
        - name: DUMPDB_HOST
          value: dumpdb
        ports:
        - containerPort: 8089 
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
          limits:
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /404.html
            port: 8089
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3            
        readinessProbe:
          httpGet:
            path: /404.html
            port: 8089
          initialDelaySeconds: 5
          periodSeconds: 5 
          timeoutSeconds: 1
          failureThreshold: 3
        securityContext:
          runAsUser: 1001
          runAsGroup: 1001        
      volumes: []
---
apiVersion: v1
kind: Service
metadata:
  name: docbase
spec:
  ports:
    - port: 8089
      targetPort: 8089
  selector:
    app.kubernetes.io/name: hcr
    control-plane: controller

