---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-hcr-adoption-latam-v1-config
  failurePolicy: Fail
  name: vconfig-v1.kb.io
  rules:
  - apiGroups:
    - hcr.adoption.latam
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - configs
  sideEffects: None
