FROM registry.access.redhat.com/rhel9/python-312

USER 0

COPY nginx.conf /etc/nginx/
COPY 404.html /data/site/

RUN dnf install -y pango nginx && \
    pip install --upgrade pip && \
    pip install mkdocs mkdocs-macros-plugin mkdocs-with-pdf weasyprint  mkdocs-minify-plugin mkdocs-mermaid2-plugin mkdocs-static-i18n[material] mkdocs-static-i18n easydict==1.2  psycopg2 mkdocs-section-index mkdocs-literate-nav pyyaml jq yq && \
    mkdir -p /data/site && \
    chown -R default /data/site /var/log/nginx /usr/share/nginx /etc/nginx

EXPOSE 8089

ENV PATH=/opt/app-root/bin:$PATH

USER 1001 

ENTRYPOINT ["nginx"]
CMD ["-g", "daemon off;"]
