FROM registry.access.redhat.com/rhel9/python-312

USER 0

RUN dnf install -y pango && \
    pip install --upgrade pip && \
    pip install mkdocs mkdocs-macros-plugin mkdocs-with-pdf weasyprint  mkdocs-minify-plugin mkdocs-mermaid2-plugin mkdocs-static-i18n[material] mkdocs-static-i18n easydict==1.2  psycopg2 mkdocs-section-index mkdocs-literate-nav pyyaml jq yq

ENV PATH=/opt/app-root/bin:$PATH

USER 1001

