---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dumpdb-docbase
  labels:
    app: dumpdb-docbase
  namespace: system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dumpdb-docbase
  template:
    metadata:
      labels:
        app: dumpdb-docbase
    spec:
      serviceAccountName: hcr-controller-manager
      containers:
      - name: dumpdb
        image: dumpdb  
        ports:
        - containerPort: 5432 
        resources:
          requests:
            memory: "128Mi"
            cpu: "200m"
          limits:
            memory: "128Mi"
        livenessProbe:
          tcpSocket:
            port: 5432  
          initialDelaySeconds: 30  
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 5432  
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 1        
        securityContext:
          runAsUser: 1001        
          runAsGroup: 1001  
      - name: docbase
        image: docbase
        ports:
        - containerPort: 8089 
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"          
        livenessProbe:
          httpGet:
            path: /404.html
            port: 8089
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3            
        readinessProbe:
          httpGet:
            path: /404.html
            port: 8089
          initialDelaySeconds: 5
          periodSeconds: 5 
          timeoutSeconds: 1
          failureThreshold: 3
        securityContext:
          runAsUser: 1001
          runAsGroup: 1001
---
apiVersion: v1
kind: Service
metadata:
  name: docbase
spec:
  ports:
    - port: 8089
      targetPort: 8089
  selector:
    app: dumpdb-docbase
