# This rule is not used by the project hcr itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to hcr.adoption.latam resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: hcr
    app.kubernetes.io/managed-by: kustomize
  name: config-viewer-role
rules:
- apiGroups:
  - hcr.adoption.latam
  resources:
  - configs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hcr.adoption.latam
  resources:
  - configs/status
  verbs:
  - get
