# This rule is not used by the project hcr itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over hcr.adoption.latam.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: hcr
    app.kubernetes.io/managed-by: kustomize
  name: config-admin-role
rules:
- apiGroups:
  - hcr.adoption.latam
  resources:
  - configs
  verbs:
  - '*'
- apiGroups:
  - hcr.adoption.latam
  resources:
  - configs/status
  verbs:
  - get
