apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: hcr-controller-manager
allowPrivilegedContainer: false
runAsUser:
  type: MustRunAs
  uid: 1001
fsGroup:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
- system:serviceaccount:hcr:hcr-controller-manager