apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: controller
allowPrivilegedContainer: false
runAsUser:
  type: MustRunAs
  uid: 1001
fsGroup:
  type: MustRunAs
  ranges:
    - min: 1001
      max: 1001
seLinuxContext:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
- system:serviceaccount:hcr:hcr-controller
