apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: controller-manager
allowPrivilegedContainer: false
runAsUser:
  type: RunAsAny
fsGroup:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
- system:serviceaccount:hcr:hcr-controller-manager