apiVersion: v1
kind: ConfigMap
metadata:
  name: kcdump
data: 
  kcdump.yaml: |-
    loglevel: info
    targetdir: /data
    # copy-to-pod: //controller-manager/dumpdb:/data/
    copy-to-pod: /test/:/tmp/data/
---    
apiVersion: batch/v1
kind: Job
metadata:
  name: kcdump
spec:
  ttlSecondsAfterFinished: 60
  template:
    spec:
      restartPolicy: Never
      backoffLimit: 0
      containers:
      - name: kcdump
        env:
        - name: "HOME"
          value: "/tmp"  
        image: quay.io/hcreport/kcdump
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /data
          name: work
          readOnly: false        
        - mountPath: /tmp/.kube/kcdump
          name: config
          readOnly: true           
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL        
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      resources:
        limits:
          memory: 640Mi
        requests:
          memory: 640Mi
      volumes:
      - name: work     
        emptyDir:
          sizeLimit: 3Gi
      - name: config
        configMap:
          name: kcdump   
      terminationGracePeriodSeconds: 10
      serviceAccountName: hcr-controller-manager
