---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - hcreport.csa.latam.redhat.com
  resources:
  - configs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hcreport.csa.latam.redhat.com
  resources:
  - configs/finalizers
  verbs:
  - update
- apiGroups:
  - hcreport.csa.latam.redhat.com
  resources:
  - configs/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webhook-manager-role
rules:
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  - mutatingwebhookconfigurations
  resourceNames:
  - ""
  - ""
  verbs:
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: reader-manager-role
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:  
  - get
  - list
  - watch
