from docker.io/postgres

ENV PGDATA=/var/lib/postgresql/pgdata
ENV POSTGRES_HOST_AUTH_METHOD=trust

COPY onefile.sql /docker-entrypoint-initdb.d/hcr_init.sql

RUN apt-get update && \
    apt-get install -y autoconf automake build-essential libtool python-dev-is-python3 postgresql-plpython3-16 jq yq && \
    /usr/local/bin/docker-ensure-initdb.sh

USER postgres

WORKDIR /var/lib/postgresql

